source:
  - dictionary/properties/**/*.yaml
log: warn
platforms:
  less:
    prefix: ds
    buildPath: dist/less/
    transformGroup: less
    files:
      - destination: brand-colors.less
        format: less/variables
        filter:
          attributes:
            category: color
            type: brand

      - destination: data-colors.less
        format: less/variables
        filter:
          attributes:
            category: color
            type: ramp

      - destination: system-colors.less
        format: less/variables
        filter:
          attributes:
            category: color
            type: system

  js:
    buildPath: dist/js/
    transformGroup: js
    prefix: ds
    files:
      - destination: brand-colors.esm.js
        format: javascript/es6
        filter:
            attributes:
              category: color
              type: brand

      - destination: system-colors.esm.js
        format: javascript/es6
        filter:
          attributes:
            category: color
            type: system

      - destination: data-colors.esm.js
        format: javascript/es6
        filter:
          attributes:
            category: color
            type: ramp

  icons:
    buildPath: dist/icons/
    prefix: ds
    transforms:
      - attribute/cti
      - name/cti/kebab
    files:
      - destination: sprites-dashboard.svg
        format: svg/sprites
        id: asset-icon-spritesheet-dashboard
        filter:
          attributes:
            category: asset
            type: icon
            item: dashboard

      - destination: sprites-player.svg
        format: svg/sprites
        id: asset-icon-spritesheet-player
        filter:
          attributes:
            category: asset
            type: icon
            item: player

      - destination: sprites-logos.svg
        format: svg/sprites
        id: asset-icon-spritesheet-logo
        filter:
          attributes:
            category: asset
            type: icon
            item: logo
