platforms:
  css:
    prefix: ds
    buildPath: dist/css/
    transformGroup: css
    files:
      - destination: brand-colors.css
        format: css/variables
        filter:
          attributes:
            category: color
            type: brand

      - destination: data-colors.css
        format: css/variables
        filter:
          attributes:
            category: color
            type: data

      - destination: system-colors.css
        format: css/variables
        filter:
          attributes:
            category: color
            type: system

      - destination: marketing-colors.css
        format: css/variables
        filter:
          attributes:
            category: color
            type: marketing

      - destination: code-colors.css
        format: css/variables
        filter:
          attributes:
            category: color
            type: code

      - destination: font-vars.css
        format: css/variables
        filter:
          attributes:
            category: global
            type: font

      - destination: layout.css
        format: css/variables
        filter:
          attributes:
            category: layout

      - destination: theme.css
        format: css/variables
        filter:
          attributes:
            category: theme
