platforms:
  scss:
    prefix: ds
    buildPath: dist/scss/
    transformGroup: scss
    files:
      - destination: brand-colors.scss
        format: scss/variables
        filter:
          attributes:
            category: color
            type: brand

      - destination: data-colors.scss
        format: scss/variables
        filter:
          attributes:
            category: color
            type: data

      - destination: system-colors.scss
        format: scss/variables
        filter:
          attributes:
            category: color
            type: system

      - destination: marketing-colors.scss
        format: scss/variables
        filter:
          attributes:
            category: color
            type: marketing

      - destination: code-colors.scss
        format: scss/variables
        filter:
          attributes:
            category: color
            type: code

      - destination: font-vars.scss
        format: scss/variables
        filter:
          attributes:
            category: global
            type: font

      - destination: layout.scss
        format: scss/variables
        filter:
          attributes:
            category: layout

      - destination: theme.scss
        format: scss/variables
        filter:
          attributes:
            category: theme
